name: ui_components
description: A package containing reusable UI components
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  utils: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
